import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

const banner = {
  animate: {
    transition: {
      delayChildren: 0.4,
      staggerChildren: 0.1,
    },
  },
};

const wordAnimation = {
  initial: {
    y: 100,
  },
  animate: {
    y: 0,
    transition: {
      ease: [0.6, 0.01, -0.05, 0.95],
      duration: 1,
    },
  },
};

const riseWithFade = {
  initial: {
    y: 100,
    opacity: 0,
  },
  animate: {
    y: 0,
    opacity: 1,
    transition: {
      ease: [0.6, 0.01, -0.05, 0.95],
      duration: 0.7,
    },
  },
};

const videoAnimation = {
  initial: {
    y: 100,
    opacity: 0,
    scale: 0.8,
  },
  animate: {
    y: 0,
    opacity: 1,
    scale: 1,
    transition: {
      ease: [0.6, 0.01, -0.05, 0.95],
      duration: 1,
    },
  },
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Robot Co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.hero}>
        <motion.h1 variants={banner} animate="animate">
          <AnimatedWords title="Helper robots for a better everyday" />
        </motion.h1>
        <motion.div
          className={styles.heroDetails}
          variants={riseWithFade}
          initial="initial"
          animate="animate"
        >
          Born from the moonshot factory, we're building a new type of robot.
          One that can learn by itself, to help anyone with (almost) anything.
        </motion.div>
      </main>
      <motion.video
        className={styles.video}
        variants={videoAnimation}
        initial="initial"
        animate="animate"
        src="/hero-video.mp4"
        loop
        autoPlay
      />
      <footer className={styles.footer}>
        <p>Copyright 2022 Robot Co. All rights reserved.</p>
      </footer>
    </div>
  );
}

const AnimatedWords = ({ title }) => {
  return (
    <motion.span variants={banner} initial="initial" animate="animate">
      {title.split(" ").map((word, idx) => (
        <div key={idx} className={styles.wordContainer}>
          <motion.span className={styles.animatedSpan} variants={wordAnimation}>
            {word + "\u00A0"}
          </motion.span>
        </div>
      ))}
    </motion.span>
  );
};
